name: ListStrap Wordpress Plugin CI/CD
on: 
  push:
    branches: [master]

jobs:
  build:
    name: Build And Publish Plugin
    runs-on: ubuntu-latest
    steps: 

      - name: Checkout To Current Changes
        id: checkout
        uses: actions/checkout@v2

      - name: Bundle
        id: bundle
        run: |
             zip -r liststrap.zip .

      - name: Publish to SVN
        id: publish
        uses: nk-o/action-wordpress-plugin-deploy@master
        env: 
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SOURCE_DIR: dist/
          SLUG: liststrap

      - name: Deploy to Server
        id: deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
